f1ap:
  cu_cp_addr: CU_CP_ADDR
  bind_addr: 0.0.0.0
f1u:
  socket:
    -
      bind_addr: 0.0.0.0
ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://*:2000,rx_port=tcp://UE_ADDR:2001,base_srate=11.52e64
  srate: 23.04
  tx_gain: 80
  rx_gain: 40
cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1
